blueprint:
  name: Yarbo Low Battery Notification
  description: >
    Send a notification when the Yarbo robot's battery drops below a configurable
    threshold while not charging.
  domain: automation
  author: markus-lassfolk
  source_url: https://github.com/markus-lassfolk/home-assistant-yarbo

  input:
    battery_sensor:
      name: Battery Sensor
      description: The Yarbo battery sensor entity.
      selector:
        entity:
          integration: yarbo
          domain: sensor
          device_class: battery

    threshold:
      name: Battery Threshold (%)
      description: Send notification when battery drops below this percentage.
      default: 20
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
          mode: slider

    notify_service:
      name: Notification Service
      description: The notify service to call (e.g. notify.mobile_app_phone).
      selector:
        text:
          multiline: false

    message:
      name: Notification Message
      description: Message to send. Use {battery} for the current battery level.
      default: "Yarbo battery is low: {battery}%"
      selector:
        text:
          multiline: false

trigger:
  - platform: numeric_state
    entity_id: !input battery_sensor
    below: !input threshold

condition:
  - condition: template
    value_template: >
      {% set device_id = device_id(trigger.entity_id) %}
      {% set charging_entity = 'binary_sensor.' ~ device_attr(device_id, 'name') | slugify ~ '_charging' %}
      {{ not is_state(charging_entity, 'on') }}

action:
  - service: !input notify_service
    data:
      title: "Yarbo Low Battery"
      message: >
        {{ (inputs.message | default('Yarbo battery is low: {battery}%'))
           | replace('{battery}', trigger.to_state.state) }}

mode: single
max_exceeded: silent
