blueprint:
  name: Yarbo Rain Pause & Resume
  description: >
    Automatically pause the Yarbo robot when rain is detected and send it to
    dock, then resume after rain stops (with a configurable delay to let the
    ground dry). When rain stops the automation re-launches the mowing job
    regardless of whether the robot docked — this is intentional so the robot
    resumes work automatically. The default threshold of 0.1 is chosen
    deliberately: using 0 would break the rain-stop trigger because
    Home Assistant's numeric_state `below: 0` only fires when the value goes
    strictly below 0, and dry sensors read exactly 0.
  domain: automation
  author: markus-lassfolk
  source_url: https://github.com/markus-lassfolk/home-assistant-yarbo

  input:
    yarbo_device:
      name: Yarbo Robot
      description: The Yarbo robot device to control.
      selector:
        device:
          integration: yarbo

    rain_sensor:
      name: Rain Sensor
      description: >
        Sensor that indicates rain. Can be the Yarbo rain sensor entity
        or any external weather sensor.
      selector:
        entity:
          domain: sensor

    rain_threshold:
      name: Rain Detection Value
      description: >
        Sensor value above which rain is considered active.
        For the Yarbo rain sensor, 0.1 is recommended: the sensor reads 0 when dry
        and a positive value when wet. Setting this to 0 would break rain-stop detection
        because `below: 0` never fires (the sensor never goes negative).
      default: 0.1
      selector:
        number:
          min: 0.01
          max: 1000
          mode: box

    resume_delay:
      name: Resume Delay (minutes)
      description: >
        Wait this many minutes after rain stops before resuming,
        to allow the ground to dry.
      default: 30
      selector:
        number:
          min: 0
          max: 120
          unit_of_measurement: min
          mode: slider

    activity_sensor:
      name: Activity Sensor
      description: The Yarbo activity sensor — used to check if robot is working.
      selector:
        entity:
          integration: yarbo
          domain: sensor

variables:
  yarbo_device_id: !input yarbo_device
  activity_entity: !input activity_sensor

trigger:
  - platform: numeric_state
    id: rain_start
    entity_id: !input rain_sensor
    above: !input rain_threshold

  - platform: numeric_state
    id: rain_stop
    entity_id: !input rain_sensor
    below: !input rain_threshold

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: rain_start
          - condition: state
            entity_id: !input activity_sensor
            state: working
        sequence:
          - service: yarbo.pause
            data:
              device_id: !input yarbo_device
          - delay:
              seconds: 5
          - service: yarbo.return_to_dock
            data:
              device_id: !input yarbo_device

      - conditions:
          - condition: trigger
            id: rain_stop
        sequence:
          - delay:
              minutes: !input resume_delay
          - condition: or
            conditions:
              - condition: state
                entity_id: !input activity_sensor
                state: idle
              - condition: state
                entity_id: !input activity_sensor
                state: charging
              - condition: state
                entity_id: !input activity_sensor
                state: paused
          - service: yarbo.resume
            data:
              device_id: !input yarbo_device

mode: restart
