blueprint:
  name: Yarbo Rain Pause & Resume
  description: >
    Automatically pause and dock the Yarbo robot when rain is detected,
    then resume after a configurable dry delay once rain stops.
    Only acts when the robot is actively executing a plan.
  domain: automation
  author: markus-lassfolk
  source_url: https://github.com/markus-lassfolk/home-assistant-yarbo

  input:
    yarbo_device:
      name: Yarbo Robot
      description: The Yarbo robot device to control.
      selector:
        device:
          integration: yarbo

    rain_sensor:
      name: Rain Sensor
      description: >
        Binary sensor that indicates rain (on = raining, off = dry).
        Can be the Yarbo built-in rain binary sensor or any HA rain/weather sensor.
      selector:
        entity:
          domain: binary_sensor

    dry_delay:
      name: Dry Delay
      description: >
        How long to wait after rain stops before resuming, to let the ground dry.
        Default is 2 hours.
      default: "02:00:00"
      selector:
        duration:

    planning_sensor:
      name: Planning Sensor
      description: >
        The Yarbo planning binary sensor — automation only acts when the robot
        is actively executing a plan (binary_sensor.*_planning is on).
      selector:
        entity:
          integration: yarbo
          domain: binary_sensor

trigger:
  - platform: state
    id: rain_start
    entity_id: !input rain_sensor
    to: "on"

  - platform: state
    id: rain_stop
    entity_id: !input rain_sensor
    to: "off"

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: rain_start
          - condition: state
            entity_id: !input planning_sensor
            state: "on"
        sequence:
          - service: yarbo.pause
            data:
              device_id: !input yarbo_device
          - delay:
              seconds: 2
          - service: yarbo.return_to_dock
            data:
              device_id: !input yarbo_device

      - conditions:
          - condition: trigger
            id: rain_stop
        sequence:
          - delay: !input dry_delay
          - condition: state
            entity_id: !input planning_sensor
            state: "on"
          - service: yarbo.resume
            data:
              device_id: !input yarbo_device

mode: restart
