name: Feature Request
description: Suggest a new feature or improvement
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it clearly.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this solve? What are you trying to do?
      placeholder: "I want to be able to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've tried?
    validations:
      required: false

  - type: dropdown
    id: head_type
    attributes:
      label: Related Head Type (if applicable)
      options:
        - All heads
        - Snow Blower
        - Lawn Mower
        - Leaf Blower
        - Smart Cover / SAM
        - Not head-specific
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
    validations:
      required: false
